AtpCore/Pages/Components/PlayerExpanded/PlayerBios.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AtpCore.Pages.Components.PlayerExpanded
{
    public class PlayerBiosModel : PageModel
    {

        public PlayerBiosData PlayerData { get; set; }

        public void OnGet()
        {
        }
    }
}

AtpCore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AtpCore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AtpCore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Logging;
using Microsoft.JSInterop;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using System.Web.Mvc;
using HtmlHelper = System.Web.Mvc.HtmlHelper;

namespace AtpCore
{
    public class IndexModel : PageModel
    {
        public List<PlayerJson> PlayerList { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {

            ViewData["title"] = "ATP Tour Top 10";

            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("https://app.atptour.com/");

            // Get data from JSON HttpContent with ReadFromJsonAsync
            var request = new HttpRequestMessage(HttpMethod.Get, "api/gateway/rankings.ranksglrollrange?fromrank=1&torank=10");
            using var response = await httpClient.SendAsync(request);

            List<PlayerJson> playerList = new List<PlayerJson>();

            if (response.IsSuccessStatusCode)
            {
                var profiles = response.Content.ReadFromJsonAsync<PlayerData>();

                foreach (PlayerJson player in profiles.Result.Data.Rankings.Players)
                {
                    playerList.Add(player);
                }
            }

            PlayerList = playerList;

            return Page();
        }
    }
}

AtpCore/Pages/Nosql.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
//using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
//using Microsoft.Azure.Documents.Client;

namespace AtpCore.Pages
{
    public class NosqlModel : PageModel
    {

        private static string endpointUrl = "https://atp-assessment.documents.azure.com:443/";
        private static string authorizationKey = "xBe1N1J70dbq84gKoerzNpPZKAkmWLLdGdRlKMAAVn3zi0clkbx1qtHxlv4wae6QhbbY4bfT9O177FW4uviwDQ==";
        static DocumentClient client = new DocumentClient(new Uri(endpointUrl), authorizationKey);
        static Database database = client.CreateDatabaseQuery().Where(x => x.Id == "atpdb").AsEnumerable().FirstOrDefault();
        DocumentCollection collection = client.CreateDocumentCollectionQuery(database.SelfLink).Where(c => c.Id == "atpdata").ToArray().FirstOrDefault();
        // Set some common query options
        FeedOptions queryOptions = new FeedOptions { MaxItemCount = -1, EnableCrossPartitionQuery = true };

        public List<NoSqlClass> FavoriteColor { get; set; } = new List<NoSqlClass>();

        public async Task<IActionResult> OnGetAsync()
        {
            List<NoSqlClass> colorsList = new List<NoSqlClass>();

            var docs = client.CreateDocumentQuery<NoSqlClass>(collection.SelfLink, queryOptions).AsEnumerable();

            foreach (var item in docs)
            {
                colorsList.Add(item);
            }

            FavoriteColor = colorsList;
            return Page();

        }

        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                NoSqlClass colorData = new NoSqlClass
                {
                    Name = Request.Form["txtboxName"],
                    Color = Request.Form["colorFavoriteColor"],
                    Time = DateTime.Now.ToString(),
                    id = Guid.NewGuid().ToString(),
                };

                await client.CreateDocumentAsync(collection.SelfLink, colorData);
            }
            catch (Exception)
            {
                throw;
            }

            if (!this.ModelState.IsValid)
            {
                // Something failed. Redisplay the form.
                return await this.OnGetAsync();
            }

            return this.RedirectToPage("/Nosql");

        }

        public async Task<IActionResult> OnPostDelete(string id, string Name)
        {
            try
            {

                await client.DeleteDocumentAsync(
                    UriFactory.CreateDocumentUri("atpdb", "atpdata", id),
                    new RequestOptions { PartitionKey = new PartitionKey(Name) });

            }
            catch (Exception)
            {
                throw;
            }

            if (!this.ModelState.IsValid)
            {
                // Something failed. Redisplay the form.
                return await this.OnGetAsync();
            }

            return this.RedirectToPage("/Nosql");

        }
    }
}

AtpCore/PlayerExpandedViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AtpCore
{
    public class PlayerExpandedViewComponent : ViewComponent
    {
        public PlayerBiography PlayerBiosFull { get; set; }

        public string PlayerId { get; set; }

        public async Task<IViewComponentResult> InvokeAsync(string PlayerId)
        {
            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("https://app.atptour.com/");

            // Get data from JSON HttpContent with ReadFromJsonAsync
            var request = new HttpRequestMessage(HttpMethod.Get, "api/gateway/players.PlayerProfileBio?playerid=" + PlayerId);
            using var response = await httpClient.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                var profile = response.Content.ReadFromJsonAsync<PlayerBiography>();

                PlayerBiosFull = profile.Result;

            }

        return View<PlayerBiography>("_PlayerBios", PlayerBiosFull);

        }
    }
}

AtpCore/PlayerViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AtpCore
{
    public class PlayerViewComponent : ViewComponent
    {
        public PlayerBiosData PlayerBios { get; set; }

        public string PlayerId { get; set; }

        public async Task<IViewComponentResult> InvokeAsync(string PlayerId)
        {
            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("https://app.atptour.com/");

            // Get data from JSON HttpContent with ReadFromJsonAsync
            var request = new HttpRequestMessage(HttpMethod.Get, "api/gateway/players.PlayerProfileBio?playerid=" + PlayerId);
            using var response = await httpClient.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                var profile = response.Content.ReadFromJsonAsync<PlayerBiography>();

                PlayerBios = profile.Result.Data;

                //PlayerData tester = profiles.Result.Data.(p => p.PlayerId == PlayerId));

                //PlayerData testerTwo = profiles.Result.Data.W


                //foreach (PlayerBiosData player in profiles.Result.Data)
                //{



                //}
            }

            //return View<PlayerBiosData>(PlayerBios);
            //return View<PlayerBiosData>("PlayerInfo", PlayerBios);

            //return View<PlayerBiosData>("_PlayerTest", PlayerBios);
            return View("_PlayerTest", PlayerBios);

        }
    }
}

AtpCore/Pages/Components/PlayerExpanded/PlayerBios.cshtml
@model PlayerBiosData
@*@model PlayerBiosModel*@
@{
}

<h1>PlayerBio.cshtml</h1>
<h1>@Model.LastName</h1>

AtpCore/Pages/Components/PlayerExpanded/_PlayerBios.cshtml
@model PlayerBiography
@{
}

@section Scripts {

    <script type="text/javascript">

        $('#playerTabs a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        })

    </script>
}

@using System.Net

@*Wait until click to generate the player info*@
@*https://swimburger.net/blog/dotnet/how-to-run-code-after-blazor-component-has-rendered*@


<!-- Nav tabs -->
<div class="panel with-nav-tabs panel-default">
    <div class="panel-heading">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#@($"about{Model.Data.PlayerId}")" aria-controls="@($"about{Model.Data.PlayerId}")" role="tab" data-toggle="tab">About @Model.Data.FirstName</a></li>
            <li role="presentation"><a href="#@($"year{Model.Data.PlayerId}")" aria-controls="@($"year{Model.Data.PlayerId}")" role="tab" data-toggle="tab">Year to Date</a></li>
            <li role="presentation"><a href="#@($"career{Model.Data.PlayerId}")" aria-controls="@($"career{Model.Data.PlayerId}")" role="tab" data-toggle="tab">Career Highlights</a></li>
        </ul>
    </div>
    <!-- Tab panes -->
    <div class="panel-body">
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="@($"about{Model.Data.PlayerId}")">
                <div class="float-right m-3">
                    <img width="70%" src="https://www.atptour.com/@(Model.Content.PlayerProfileDetails.PlayerGladiatorUrl)" alt="@Model.Data.FirstName @Model.Data.LastName" />
                </div>
                <div class="m-3">
                    @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioPersonal))
                </div>
            </div>
            <div role="tabpanel" class="tab-pane fade in" id="@($"year{Model.Data.PlayerId}")">
                <div class="m-3">
                    @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioYearToDate))
                </div>
            </div>
            <div role="tabpanel" class="tab-pane fade in" id="@($"career{Model.Data.PlayerId}")">
                <div class="m-3">
                    @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioCareerHighlights))
                </div>
            </div>
        </div>
    </div>
</div>

        @*<div class="col-auto">
                <div class="float-right m-3">
                    <img width="70%" src="https://www.atptour.com/@(Model.Content.PlayerProfileDetails.PlayerGladiatorUrl)" alt="@Model.Data.FirstName @Model.Data.LastName" />
                </div>
                <div class="m-3">
                    <h4>About @Model.Data. @Model.Data.LastName</h4>
                    @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioPersonal))
                </div>
                <div class="m-3">
                    <h4>Career Highlights</h4>
                    @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioCareerHighlights))
                </div>
            </div>*@

AtpCore/Pages/Components/PlayerExpanded/_PlayerTest.cshtml
@model PlayerBiography
@{
}

@using System.Net

@*Wait until click to generate the player info*@
@*https://swimburger.net/blog/dotnet/how-to-run-code-after-blazor-component-has-rendered*@

<div class="col-auto">
    <div class="float-right m-3">
        <img width="70%" src="https://www.atptour.com/@(Model.Content.PlayerProfileDetails.PlayerGladiatorUrl)" alt="@Model.Data.FirstName @Model.Data.LastName" />
    </div>
    <div class="m-3">
        <h4>About @Model.Data.FirstName @Model.Data.LastName</h4>
        @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioPersonal))
    </div>
    <div class="m-3">
        <h4>Career Highlights</h4>
        @Html.Raw(@WebUtility.HtmlDecode(Model.Data.BioCareerHighlights))
    </div>
</div>

AtpCore/Pages/Index.cshtml
@page "/"
@model IndexModel
@{
    ViewData["Title"] = "Top Ten";
}

@section Scripts {

    <script type="text/javascript">

        let checkboxValues = JSON.parse(getCookieValue('favorite-players')) || {};

        //Makes a favorites cookie
        function favoritePlayersCookieCreate(sender, args) {
            const $checkboxes = $('input.favorite-player[type="checkbox"]');
            const expireDate = new Date(new Date().setFullYear(new Date().getFullYear() + 1));

            $checkboxes.on("change", function () {
                $checkboxes.each(function () {
                    checkboxValues[this.value] = this.checked;
                });
                document.cookie = `favorite-players=${JSON.stringify(checkboxValues)}; expires=${expireDate}; path=/`;
            });
        }

        function getCookieValue(name) {
            let nameString = name + "=";
            const value = document.cookie.split(";").filter(item => {
                return item.includes(nameString);
            })
            if (value != "") {
                console.log(value[0].substring(nameString.length, value[0].length));
                return value[0].substring(nameString.length, value[0].length);
            }
            return false;
        }

        //Check favorites on page load
        $.each(checkboxValues, function (key, value) {
            $('input.favorite-player[type="checkbox"][value="' + key + '"]').prop('checked', value);
        });

        function togglePlayerInfo(element) {
            $(element).toggleClass("additional-row-td");
        }

        function favoritesToggle() {
            if ($('input.switch-input[type="checkbox"]').is(':checked')) {
                $.each(checkboxValues, function (key, value) {
                    if (!value) {
                        $('tr.' + key).addClass("hidden");
                    }
                });
            } else {
                $('tr.hidden').removeClass("hidden");
            }
        }

    </script>
}


<div class="row" id="content">
    <div class="col-xs-6">
        <h1>@ViewData["title"]</h1>
    </div>
    <div class="col-xs-6">
        <div class="float-right title-margin">
            Only Show Favorite Players
            <div class="switch">
                <input id="switch-1" type="checkbox" class="switch-input" onclick="favoritesToggle()" />
                <label for="switch-1" class="switch-label">Search</label>
            </div>
        </div>
    </div>

    <table class="table table-striped border">
        <tr class="table-secondary">
            <th class="text-center">
                @Html.DisplayNameFor(m => m.PlayerList[0].Rank)
            </th>
            <th class="text-center">
                Player
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(m => m.PlayerList[0].Points)
            </th>
            <th class="text-center">
                Previous Rank
            </th>
            <th class="text-center">
                Age
            </th>
            <th class="text-center">
                Country
            </th>
            <th class="text-center">
                Add to Favorites
            </th>
        </tr>

        @foreach (var item in Model.PlayerList)
        {
            <tr class="text-center @item.FirstName@item.LastName">
                <td class="player-rank">
                    @Html.DisplayFor(modelItem => item.Rank)<br />
                    <a class="player-bio" style="font-size: 0.35em" role="button" data-toggle="collapse" href="#@($"{item.PlayerId}Accordian")" onclick="togglePlayerInfo('@($"#{item.PlayerId}Row")')" aria-controls="@($"{item.PlayerId}Accordian")" aria-expanded="false">Info</a>
                </td>
                <td class="player-name">
                    <img width="30%" src="https://www.atptour.com/@(item.PlayerHeadshotImageCmsUrl)" alt="@item.FirstName @item.LastName" /><br />
                    @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)<br />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Points)<br />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrevRank)<br />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AgeAtRankDate)<br />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CountryName)<br />
                </td>
                <td>
                    <input type="checkbox" class="favorite-player" onclick="favoritePlayersCookieCreate()" value="@item.FirstName@item.LastName" name="favorite" />
                </td>
            </tr>
            <tr class="@item.FirstName@item.LastName">
                <td id="@($"{item.PlayerId}Row")" colspan="7">
                    <div id="@($"{item.PlayerId}Accordian")" class="collapse">
                        @await Component.InvokeAsync("PlayerExpanded", new { PlayerId = @item.PlayerId })
                    </div>
                </td>
            </tr>
        }
    </table>
</div>

AtpCore/Pages/Nosql.cshtml
@page
@model AtpCore.Pages.NosqlModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container-fluid">
    <div class="row" id="content">
        <h1>What's your favorite color?</h1>
    </div>
    <div class="row">
        <div class="col-sm">
            <form method="post">
                <div class="form-group">
                    <label for="txtboxName">What is your name?</label>
                    <input type="text" required id="txtboxName" class="form-control" placeholder="Buddy the Elf" name="txtboxName">
                </div>
                <div class="form-group">
                    <label for="colorFavoriteColor">What's your favorite color?</label><br />
                    <input type="color" id="colorFavoriteColor" class="" name="colorFavoriteColor">
                </div>
                <input class="btn btn-secondary" type="submit" value="Submit">
            </form>
        </div>
        <div class="col-sm">
            <label>Results</label>
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th class="text-center">
                       Name
                    </th>
                    <th class="text-center">
                        Color
                    </th>
                    <th class="text-center">
                        Delete
                    </th>
                </tr>

                @foreach (var item in Model.FavoriteColor)
                {
                    <tr>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td style="background-color: @item.Color;">
                        </td>
                        <td class="text-center">
                            <form method="post">
                                <input class="btn btn-outline-danger show-on-hover" asp-page-handler="Delete" type="submit" value="Delete">
                                <input type="hidden" name="id" value="@item.id" />
                                <input type="hidden" name="Name" value="@item.Name" />
                            </form>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

AtpCore/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ATP Tour Assessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ATP Tour Assessment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" id="menu-home">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Top Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Nosql">No SQL Example</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2020 - Stephen Moule
        </div>
    </footer>

    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>